name: Build plugin pre-release

on:
  release:
    types: [ prereleased ]

jobs:
  build:
    name: Build plugin asset
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install composer dependencies
        uses: php-actions/composer@v2
        with:
          dev: no

      - name: Generate plugin asset
        run: |
          rsync -rc --exclude-from="$GITHUB_WORKSPACE/.distignore" "$GITHUB_WORKSPACE/" release/ --delete --delete-excluded
          cd "${GITHUB_WORKSPACE}/release" || exit
          zip -r "${GITHUB_WORKSPACE}/host-webfonts-local.zip" .

      - name: Attach asset to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{github.workspace}}/host-webfonts-local.zip
          asset_name: host-webfonts-local.zip
          asset_content_type: application/zip
